apiVersion: networking.k8s.io/v1 #changed
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2 #changed 
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend: 
              service:
                name: client-cluster-ip-service
                port:
                  number:  3000
          - path: /api(/|$)(.*) #changed
            pathType: ImplementationSpecific
            backend:
              service:
                name: server-cluster-ip-service
                port:
                  number: 5000
